/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cloudmersive.client;

import com.cloudmersive.client.invoker.ApiException;
import java.io.File;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ConvertDataApi
 */
@Ignore
public class ConvertDataApiTest {

    private final ConvertDataApi api = new ConvertDataApi();

    
    /**
     * Convert CSV to JSON conversion
     *
     * Convert a CSV file to a JSON object array
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void convertDataCsvToJsonTest() throws ApiException {
        File inputFile = null;
        Object response = api.convertDataCsvToJson(inputFile);

        // TODO: test validations
    }
    
    /**
     * Convert JSON to XML conversion
     *
     * Convert a JSON object into XML
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void convertDataJsonToXmlTest() throws ApiException {
        Object jsonObject = null;
        Object response = api.convertDataJsonToXml(jsonObject);

        // TODO: test validations
    }
    
    /**
     * Convert Excel (97-2003) XLS to JSON conversion
     *
     * Convert an Excel (97-2003) XLS file to a JSON object array
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void convertDataXlsToJsonTest() throws ApiException {
        File inputFile = null;
        Object response = api.convertDataXlsToJson(inputFile);

        // TODO: test validations
    }
    
    /**
     * Convert Excel XLSX to JSON conversion
     *
     * Convert an Excel XLSX file to a JSON object array
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void convertDataXlsxToJsonTest() throws ApiException {
        File inputFile = null;
        Object response = api.convertDataXlsxToJson(inputFile);

        // TODO: test validations
    }
    
    /**
     * Convert XML to JSON conversion
     *
     * Convert an XML string or file into JSON
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void convertDataXmlToJsonTest() throws ApiException {
        File inputFile = null;
        Object response = api.convertDataXmlToJson(inputFile);

        // TODO: test validations
    }
    
}
