/*
 * convertapi
 * Convert API lets you effortlessly convert file formats and types.
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.cloudmersive.client;

import com.cloudmersive.client.invoker.ApiException;
import java.io.File;
import com.cloudmersive.client.model.ReplaceStringRequest;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EditDocumentApi
 */
@Ignore
public class EditDocumentApiTest {

    private final EditDocumentApi api = new EditDocumentApi();

    
    /**
     * Begin editing a document
     *
     * Uploads a document to Cloudmersive to begin a series of one or more editing operations
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editDocumentBeginEditingTest() throws ApiException {
        File inputFile = null;
        String response = api.editDocumentBeginEditing(inputFile);

        // TODO: test validations
    }
    
    /**
     * Replace string in DOCX
     *
     * Replace all instances of a string in an Office Word Document (docx)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editDocumentDocxReplaceTest() throws ApiException {
        ReplaceStringRequest reqConfig = null;
        byte[] response = api.editDocumentDocxReplace(reqConfig);

        // TODO: test validations
    }
    
    /**
     * Replace string in PPTX
     *
     * Replace all instances of a string in an Office PowerPoint Document (pptx)
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void editDocumentPptxReplaceTest() throws ApiException {
        ReplaceStringRequest reqConfig = null;
        byte[] response = api.editDocumentPptxReplace(reqConfig);

        // TODO: test validations
    }
    
}
